# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go get
        working-directory: src
      - run: go test ./...
        working-directory: src
  docker_build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1.6.0
        with:
          username: burdikov
          password: ${{ secrets.DOCKERHUBTOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: burdikov/godrunk:latest
